require(['jquery','ajax','jquery.cookie','search','index','goods','banner','banner2','timeout','sj','index1','floor','login'],function($,ajax,cookie,search,index,goods,banner,banner2,timeout,sj,index1,floor,login){
	search.init({
		search:'.search',
		btn:'.btn',
		ts:'.ts',
		ts2:'.ts2',
		url:"https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su",
	});
	index.init({
		ej:'.ej',
		dj:'.dj',
		xb:'.xb',
	})
	goods.init({
		xiala:".xiala",
		search2:".search2",
		label:'.label',
		nr:".nr",
	})
	banner.init({
		banner:'.banner',
		items:'.items',
		left:'.left',
		right:'.right',
		xd:'.xd',
	})
	banner2.init({
		lb:'.lb',
		left2:'.left2',
		right2:'.right2',
	});
	timeout.init({
		hour:'.hour',
		minute:'.minute',
		second:'.second',
	})
	sj.init({
		sp:".sp"
	})
	index1.init({
		product:'.product',
		go:'.go',
	})
	floor.init({
		f1:".f1",
		f2:".f2",
		floor:'#floor',
		html:'html',
	})
	login.init({
		quicklogin:".quicklogin",
		mymatou:".mymatou",
		btn:'.btn',
		txt:'.txt',
		pass:'.pass',
		ts1:'.ts1',
		ts2:'.ts2',
		login:'.login'
	})
})
